version: '3'

services:
  db:
    container_name: 'handball_db'
    image: 'mysql:8.0-debian'
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./scripts:/home/node/app/scripts
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    entrypoint: /bin/sh './scripts/be-node-dev.sh'
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
    depends_on:
      - db
    links:
      - db

volumes:
  my-db:
